import { Incident, AppNotification } from './types';

/**
 * MARIS Maritime AI Intelligence Surveillance Incidents
 * Matching command center operations: Northern Europe, Mediterranean, Atlantic, and South America
 */
export const mockIncidents: Incident[] = [
  {
    id: 'SPILL-042',
    incidentCode: 'SPILL-042',
    time: '19 Jan 2026',
    timestamp: '2026-01-19T14:50:00Z',
    bleetioun: 'SPILL-042',
    location: 'Bay of Bengal',
    statusBadge: 'Detected',
    status: 'Confirmed SAR Slick',
    incidentNumber: 'SPILL-042-BOB',
    incidentCost: '840,000',
    cost: 840000,
    maritimeTraffic: '32 Vessels Analyzed',
    lat: 14.85,
    latitude: 14.85,
    lng: 88.25,
    longitude: 88.25,
    type: 'Oil Spill',
    globeX: 72,
    globeY: 42,
    severity: 'high',
    associatedRouteIds: [
      'route-india-malacca',
      'route-colombo-singapore',
    ],
    timelineHourStart: 10,
    nearestPort: 'Port of Paradip / Vizag',
    vesselsInArea: 32,
    estimatedSpillLiters: '42.8 km² (4–7 hrs old)',
    currentVectorAngle: 48, // NE current drift
    currentVectorName: 'Bay of Bengal Drift // 1.2 m/s NE',
    zone: 'Indian Ocean / Bay of Bengal Sector',
    caprenisData: [
      { time: '08:00', value: 12 },
      { time: '10:24', value: 38 },
      { time: '12:00', value: 64 },
      { time: '14:50', value: 92 },
      { time: '16:00', value: 88 },
      { time: '18:00', value: 82 },
      { time: '20:00', value: 74 },
      { time: '22:00', value: 65 },
    ],
    graphsData: [
      { time: '08:00', value: 120 },
      { time: '10:24', value: 350 },
      { time: '12:00', value: 680 },
      { time: '14:50', value: 1040 },
      { time: '16:00', value: 1180 },
      { time: '18:00', value: 1250 },
      { time: '20:00', value: 1100 },
      { time: '22:00', value: 950 },
    ],
    investigationDetails: {
      vesselName: 'NORDIC STAR',
      imo: 'IMO 9482190',
      flag: 'Liberia [LR]',
      cargoType: 'Heavy Crude Petroleum',
      estimatedSpillVolume: '42.8 km² / Est. 4–7 hours old',
      containmentStatus: 'Simulated Rapid Response Deployment Active',
      sensorTelemetry: 'Copernicus Sentinel-1 SAR Reflectance (92% Confidence)',
      windDriftVector: 'WSW 14 kn / Ocean Surface Drift 1.2 m/s NE',
      assignedUnits: [
        'ICGS Samudra Prahari (Pollution Control Vessel)',
        'Indian Coast Guard Dornier 228 Maritime Patrol',
        'Bay of Bengal Rapid Skimmer Unit 02',
      ],
    },
  },
  {
    id: 'SPILL-041',
    incidentCode: 'SPILL-041',
    time: '19 Jan 2021',
    timestamp: '2021-01-19T14:32:00Z',
    bleetioun: 'SPILL-041',
    location: 'Maritime AI Intelligence',
    statusBadge: 'Umrethare',
    status: 'ACTIVE',
    incidentNumber: '9 Jan-041',
    incidentCost: '184,200',
    cost: 184200,
    maritimeTraffic: '28.450M',
    lat: 36.8,
    latitude: 36.8,
    lng: 16.5,
    longitude: 16.5,
    type: 'Tanker Leak',
    globeX: 68,
    globeY: 38,
    severity: 'high',
    associatedRouteIds: [
      'route-europe-med',
      'route-med-middle-east',
    ],
    timelineHourStart: 14,
    nearestPort: 'Augusta / Sicily',
    vesselsInArea: 44,
    estimatedSpillLiters: '184,200 L',
    currentVectorAngle: 110,
    currentVectorName: 'Ionian Coastal Jet // 1.6 kn SE',
    zone: 'Mediterranean Basin / Ionian Sea',
    caprenisData: [
      { time: '00:00', value: 18 },
      { time: '04:00', value: 32 },
      { time: '08:00', value: 55 },
      { time: '12:00', value: 72 },
      { time: '16:00', value: 94 },
      { time: '18:00', value: 82 },
      { time: '20:00', value: 64 },
      { time: '22:00', value: 45 },
    ],
    graphsData: [
      { time: '00:00', value: 180 },
      { time: '04:00', value: 290 },
      { time: '08:00', value: 540 },
      { time: '12:00', value: 810 },
      { time: '16:00', value: 1080 },
      { time: '18:00', value: 950 },
      { time: '20:00', value: 710 },
      { time: '22:00', value: 520 },
    ],
    investigationDetails: {
      vesselName: 'MT Mediterranean Star',
      imo: 'IMO 9741299',
      flag: 'Malta [MT]',
      cargoType: 'Bunker Fuel Oil IFO 380',
      estimatedSpillVolume: '184,200 Liters / Sheen 12.6 km²',
      containmentStatus: 'Chemical barrier and skimmers deployed from Augusta base',
      sensorTelemetry: 'MODIS Thermal Anomaly Detection High Confidence',
      windDriftVector: '11 kts NW / Offshore Current 1.6 kts SE',
      assignedUnits: [
        'Guardia Costiera CP 904',
        'REMPEC Rapid Response Tug Alpha',
        'Helo SAR AW139 Catania',
      ],
    },
  },
  {
    id: 'SPILL-039',
    incidentCode: 'SPILL-039',
    time: '19 Jan 2021',
    timestamp: '2021-01-19T11:05:00Z',
    bleetioun: 'SPILL-039',
    location: 'Maritime AI Intelligence',
    statusBadge: 'Umosthare',
    status: 'MONITORED',
    incidentNumber: '9 Jan-039',
    incidentCost: '92,450',
    cost: 92450,
    maritimeTraffic: '15.110M',
    lat: 43.5,
    latitude: 43.5,
    lng: -20.2,
    longitude: -20.2,
    type: 'Marine Oil Spill',
    globeX: 42,
    globeY: 48,
    severity: 'medium',
    associatedRouteIds: [
      'route-na-europe',
      'route-atlantic-trunk',
    ],
    timelineHourStart: 11,
    nearestPort: 'Ponta Delgada (Azores)',
    vesselsInArea: 14,
    estimatedSpillLiters: '92,450 L',
    currentVectorAngle: 85,
    currentVectorName: 'North Atlantic Drift // 1.2 kn E',
    zone: 'North Atlantic High Seas Corridor',
    caprenisData: [
      { time: '00:00', value: 14 },
      { time: '04:00', value: 26 },
      { time: '08:00', value: 40 },
      { time: '12:00', value: 68 },
      { time: '16:00', value: 55 },
      { time: '18:00', value: 48 },
      { time: '20:00', value: 36 },
      { time: '22:00', value: 24 },
    ],
    graphsData: [
      { time: '00:00', value: 150 },
      { time: '04:00', value: 240 },
      { time: '08:00', value: 420 },
      { time: '12:00', value: 760 },
      { time: '16:00', value: 620 },
      { time: '18:00', value: 510 },
      { time: '20:00', value: 380 },
      { time: '22:00', value: 260 },
    ],
    investigationDetails: {
      vesselName: 'MT Atlantic Pioneer',
      imo: 'IMO 9912040',
      flag: 'Liberia [LR]',
      cargoType: 'Marine Gasoil (MGO)',
      estimatedSpillVolume: '92,450 Liters / Dissipating into outer deep waters',
      containmentStatus: 'Natural dissipation monitored via orbital SAR satellite passes',
      sensorTelemetry: 'Sentinel-1B radar backscatter analysis',
      windDriftVector: '14 kts W / Swell 2.1m',
      assignedUnits: [
        'Portuguese Navy Corvette NRP Antonio Enes',
        'Azores Maritime Surveillance Air Unit',
      ],
    },
  },
  {
    id: 'SPILL-031',
    incidentCode: 'SPILL-031',
    time: '20 Jan 2021',
    timestamp: '2021-01-20T03:45:00Z',
    bleetioun: 'SPILL-031',
    location: 'Maritime AI Intelligence',
    statusBadge: 'HIGH RISK',
    status: 'ACTIVE',
    incidentNumber: '9 Jan-031',
    incidentCost: '412,900',
    cost: 412900,
    maritimeTraffic: '18.890M',
    lat: -24.2,
    latitude: -24.2,
    lng: -43.8,
    longitude: -43.8,
    type: 'Fuel Leakage',
    globeX: 43,
    globeY: 72,
    severity: 'high',
    associatedRouteIds: [
      'route-sa-europe',
      'route-atlantic-trunk',
    ],
    timelineHourStart: 3,
    nearestPort: 'Port of Santos',
    vesselsInArea: 28,
    estimatedSpillLiters: '215,600 L',
    currentVectorAngle: 210,
    currentVectorName: 'Brazil Current // 1.9 kn SSW',
    zone: 'South America / Santos Basin',
    caprenisData: [
      { time: '00:00', value: 48 },
      { time: '04:00', value: 92 },
      { time: '08:00', value: 80 },
      { time: '12:00', value: 95 },
      { time: '16:00', value: 70 },
      { time: '18:00', value: 85 },
      { time: '20:00', value: 60 },
      { time: '22:00', value: 45 },
    ],
    graphsData: [
      { time: '00:00', value: 340 },
      { time: '04:00', value: 980 },
      { time: '08:00', value: 850 },
      { time: '12:00', value: 1100 },
      { time: '16:00', value: 780 },
      { time: '18:00', value: 920 },
      { time: '20:00', value: 640 },
      { time: '22:00', value: 460 },
    ],
    investigationDetails: {
      vesselName: 'MT Guanabara Express',
      imo: 'IMO 9855123',
      flag: 'Brazil [BR]',
      cargoType: 'Heavy Crude (Lula Field)',
      estimatedSpillVolume: '215,600 Liters / Plume 14.8 km²',
      containmentStatus: 'Petrobras Spill Response Unit deploying ocean skimmers',
      sensorTelemetry: 'CBERS-4A Optical & SAR multi-pass detection',
      windDriftVector: '13 kts NE / Wave Crest 1.6m',
      assignedUnits: [
        'Brazilian Navy Patrol Vessel NPa Maracanã',
        'Santos Port Environmental Tug OSRV Albatroz',
        'Aeronaval Surveillance Helicopter UH-15',
      ],
    },
  },
  {
    id: 'SPILL-IND-042',
    incidentCode: 'SPILL-IND-042',
    time: '20 Jan 2021',
    timestamp: '2021-01-20T06:15:00Z',
    bleetioun: 'SPILL-IND-042',
    location: 'Maritime AI Intelligence',
    statusBadge: 'HIGH RISK',
    status: 'ACTIVE',
    incidentNumber: '9 Jan-IND-042',
    incidentCost: '318,400',
    cost: 318400,
    maritimeTraffic: '24.120M',
    lat: 19.38,
    latitude: 19.38,
    lng: 71.85,
    longitude: 71.85,
    type: 'Crude Discharge',
    globeX: 74,
    globeY: 42,
    severity: 'critical',
    associatedRouteIds: [
      'route-gulf-india',
      'route-india-coastal',
      'route-india-malacca',
    ],
    timelineHourStart: 6,
    nearestPort: 'Jawaharlal Nehru Port (JNPT Mumbai)',
    vesselsInArea: 38,
    estimatedSpillLiters: '294,000 L',
    currentVectorAngle: 135, // Arabian Sea current towards Konkan coast
    currentVectorName: 'West India Coastal Current // 1.5 kn SE',
    zone: 'Arabian Sea / Mumbai High Offshore Basin',
    caprenisData: [
      { time: '00:00', value: 30 },
      { time: '04:00', value: 54 },
      { time: '08:00', value: 95 },
      { time: '12:00', value: 88 },
      { time: '16:00', value: 91 },
      { time: '18:00', value: 84 },
      { time: '20:00', value: 72 },
      { time: '22:00', value: 58 },
    ],
    graphsData: [
      { time: '00:00', value: 240 },
      { time: '04:00', value: 520 },
      { time: '08:00', value: 1180 },
      { time: '12:00', value: 960 },
      { time: '16:00', value: 1040 },
      { time: '18:00', value: 880 },
      { time: '20:00', value: 720 },
      { time: '22:00', value: 560 },
    ],
    investigationDetails: {
      vesselName: 'MT Desh Shanti (In Area)',
      imo: 'IMO 9272905',
      flag: 'India [IN]',
      cargoType: 'Arabian Light Crude Oil',
      estimatedSpillVolume: '294,000 Liters / Slick 16.2 km²',
      containmentStatus: 'Indian Coast Guard pollution response vessel deployed ocean booms',
      sensorTelemetry: 'RISAT-1A SAR radar polarimetry + Copernicus Sentinel-1 confirmation',
      windDriftVector: '14 kts NW / Coastal Current 1.5 kts SE',
      assignedUnits: [
        'ICGS Samarth (Offshore Patrol Vessel)',
        'Indian Coast Guard Dornier 228 (Daman Squadron)',
        'JNPT Emergency Oil Spill Response Tug 02',
      ],
    },
  },
];

export { INDIAN_VESSELS } from './data/indianVessels';

export const timelineTicks: string[] = [
  '00:00', '02:00', '04:00', '06:00', '08:00', '10:00',
  '12:00', '14:00', '16:00', '18:00', '20:00', '22:00', '24:00'
];

export const mockNotifications: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'CRITICAL: SPILL-042 Confirmed in Northern Europe',
    description: 'Satellite SAR telemetry detected crude sheen over North Sea shipping corridor.',
    timeAgo: '4 mins ago',
    severity: 'critical',
    unread: true,
    incidentId: 'SPILL-042',
  },
  {
    id: 'notif-2',
    title: 'SPILL-041 Mediterranean Containment Initiated',
    description: 'Guardia Costiera response tug deployed chemical booms off Sicily.',
    timeAgo: '18 mins ago',
    severity: 'warning',
    unread: true,
    incidentId: 'SPILL-041',
  },
  {
    id: 'notif-3',
    title: 'SPILL-031 Santos Basin Trajectory Alert',
    description: 'Brazil current vector 1.9 kn SSW; containment active.',
    timeAgo: '42 mins ago',
    severity: 'info',
    unread: false,
    incidentId: 'SPILL-031',
  },
];
